[package]
name = "hexcalc"
version = "0.2.0"
authors = ["Kurt Kanzenbach <kurt@kmk-computers.de>"]

[dependencies]
pest = "2.7.2"
pest_derive = "2.7.2"
redox_liner = "0.5.1"
termion = "1.5.1"
clap = "2.32.0"
libc = "0.2"
